module.exports = {
    playHelp: "Dodaje utwór/playlistę do kolejki.",
    helpHelp: "Pomoc dla komend",
    pauseHelp: "Wstrzymuje odtwarzanie muzyki.",
    resumeHelp: "Wznawia odtwarzanie muzyki.",
    leaveHelp: "Opuszcza kanał głosowy.",
    queueHelp: "Wyświetla aktualną kolejkę.",
    npHelp: "Wyświetla aktualnie odtwarzany utwór.",
    loopHelp: "Zapętla kolejkę.",
    searchHelp: "Szuka 10 filmów z YouTube.",
    clearHelp: "Czyści całą kolejkę.",
    volumeHelp: "Zmienia głośność bota.",
    removeHelp: "Usuwa wybraną piosenkę z kolejki",
    skipHelp: "Pomija piosenkę lub wiele piosenek.",
    cooldownWait: "Musisz odczekać zanmim znów będziesz mógł użyć komendy.",
    notInVC: "Nie jesteś na kanale głosowym.",
    noMusicPlayed: "Żadna muzyka nie jest odtwarzana.",
    vcMismatch: "Musisz być na tym samym kanale głosowym co bot.",
    pauseReject: "Nie możesz pauzować kolejek.",
    skipped: "Pominięto piosenkę.",
    paused: "Odtwarzanie wstrzymane.",
    noVideo: "Nie podano co mam odtworzyć.",
    maxQueue: "Osiągnięto limit kolejki!",
    playlistSearching: "Szukam utworów z playlisty.",
    playlistFetchZero: "Nie można wczytać utworów z playlisty.",
    playlistFetchOverLimit: "Za dużo utworów w playliście! Limit wynosi 50.",
    playlistQueuedOne: "Dodano piosenkę.",
    playlistQueued: "Dodano ",
    playlistSongs: " piosenek.",
    playSearching: "Szukam ",
    fail: "Coś poszło nie tak. Spróbuj ponownie!",
    queueAdd: "Dodaję do kolejki",
    queuedOn: "Dodano",
    requestedBy: "Dodał ",
    requestedByWithoutSpace: "Dodał",
    nowPlaying: "Teraz gram",
    commands: "Komendy",
    use: "Użyj ",
    embedError: "Błąd!",
    embedSearch: "Szukam!",
    durationTime: "Czas trwania",
    time: "Czas:",
    playbackFinished: "Odtwarzanie zakończone.",
    noOneinVC: "Nikogo nie ma na kanale, wychodzę...",
    queueErrCon: "Coś jest nie tak z połączeniem, próbuję wznowić kolejkę...",
    queueErr: "Coś się zepsuło, próbuję wznowić kolejkę...",
    queueErrNotFound: "Nie znaleziono kolejki na tym serwerze!",
    vcErrNoPerm: "Nie mam uprawnień aby dołączyć do kanału głosowego!",
    loopOnce: "Zapętlam pojedynczy utwór!",
    loopQueue: "Zapętlam całą kolejkę!",
    loopOff: "Wyłączono zapętlanie!",
    removed: "Usunięto:",
    helpDescription: "[komenda]\` aby wyświetlić pomoc komendy. Każdy z rolą",
    helpDescription2: "może użyć każdej komendy.",
    helpTitle: "= Komendy Muzyczne =",
    commandNotValid: "nie jest poprawną komendą.",
    aliases: "Aliasy",
    skipYouNotQueued: "Nie możesz pominąć utworu którego nie dodałeś.",
    skipSingleLoop: "Nie możesz pominąć zapętlanego utworu.",
    pauseAlready: "Muzyka już jest zapauzowana.",
    queueYouNotResume: "Nie możesz wnzawiać kolejek.",
    playAlready: "Muzyka już jest odtwarzana.",
    playResume: "Wznowiono odtwarzanie.",
    vcBotNot: "Nie jestem na kanale głosowym.",
    vcLeft: "Opuściłem kanał głosowy.",
    vcUserNoPerm: "Nie masz uprawnień, aby to zrobić.",
    playNoMusic: "Żadna muzyka nie jest odtwarzana.",
    queueEmpty: "Kolejka jest pusta.",
    playNoVideoFound: "Nie znaleziono wideo.",
    queuedSongs: "Piosenki w kolejce",
    page: "Strona",
    of: "z",
    playNoVideoSpecified: "Nie podano wideo.",
    queueMax: "Osiągnięto limit kolejki!",
    searching: "Szukam:",
    searchFail: "Nie mogłem pobrać wyników wyszukiwania.",
    chooseVideo: "Wybierz wideo",
    searchBy: "Szukał:",
    cancel: "anuluj",
    searchCanceled: "Anulowano wyszukiwanie.",
    typeCancel: "Wpisz anuluj, aby anulować",
    userNoPerm: "Tylko administratorzy lub DJ mogą to zrobić.",
    volumeNoSpecified: "Nie podano głośności.",
    volumeErrRange: "Poziom głośności musi wynosić od 1 do 200.",
    volumeChanged: "Głośność ustawiono na",
    removeNoPosition: "Nie podano które video mam usunąć.",
    removeErrClearCurr: "Nie możesz usunąć z kolejki obecnie grającego utworu.",
    removeErr: "Nie możesz usunąć tego utworu."
}
