module.exports = {
    LANG_ID: "pl-PL",
    playHelp: "Dodaje utwór/playlistę do kolejki.",
    helpHelp: "Pomoc dla komend",
    pauseHelp: "Wstrzymuje odtwarzanie muzyki.",
    resumeHelp: "Wznawia odtwarzanie muzyki.",
    leaveHelp: "Opuszcza kanał głosowy.",
    queueHelp: "Wyświetla aktualną kolejkę.",
    npHelp: "Wyświetla aktualnie odtwarzany utwór.",
    loopHelp: "Zapętla kolejkę.",
    searchHelp: "Szuka 10 filmów z YouTube.",
    clearHelp: "Czyści całą kolejkę.",
    volumeHelp: "Zmienia głośność bota.",
    removeHelp: "Usuwa wybraną piosenkę z kolejki",
    skipHelp: "Pomija piosenkę lub wiele piosenek.",
    cooldownWait: "Musisz odczekać zanmim znów będziesz mógł użyć komendy.",
    notInVC: "Nie jesteś na kanale głosowym.",
    noMusicPlayed: "Żadna muzyka nie jest odtwarzana.",
    vcMismatch: "Musisz być na tym samym kanale głosowym co bot.",
    pauseReject: "Nie możesz pauzować kolejek.",
    skipped: "Pominięto piosenkę.",
    paused: "Odtwarzanie wstrzymane.",
    noVideo: "Nie podano co mam odtworzyć.",
    maxQueue: "Osiągnięto limit kolejki!",
    playlistSearching: "Szukam utworów z playlisty.",
    playlistFetchZero: "Nie można wczytać utworów z playlisty.",
    playlistFetchOverLimit: "Za dużo utworów w playliście! Limit wynosi 50.",
    playlistQueuedOne: "Dodano piosenkę.",
    playlistQueued: "Dodano ",
    playlistSongs: " piosenek.",
    playSearching: "Szukam ",
    fail: "Coś poszło nie tak. Spróbuj ponownie!",
    queueAdd: "Dodaję do kolejki",
    queuedOn: "Dodano",
    requestedBy: "Dodał ",
    requestedByWithoutSpace: "Dodał",
    nowPlaying: "Teraz gram",
    commands: "Komendy",
    use: "Użyj ",
    embedError: "Błąd!",
    embedSearch: "Szukam!",
    durationTime: "Czas trwania",
    time: "Czas:",
    playbackFinished: "Odtwarzanie zakończone.",
    noOneinVC: "Nikogo nie ma na kanale, wychodzę...",
    queueErrCon: "Coś jest nie tak z połączeniem, próbuję wznowić kolejkę...",
    queueErr: "Coś się zepsuło, próbuję wznowić kolejkę...",
    queueErrNotFound: "Nie znaleziono kolejki na tym serwerze!",
    vcErrNoPerm: "Nie mam uprawnień aby dołączyć do kanału głosowego!",
    loopOnce: "Zapętlam pojedynczy utwór!",
    loopQueue: "Zapętlam całą kolejkę!",
    loopOff: "Wyłączono zapętlanie!",
    removed: "Usunięto:"
}
